= DMPP Initial Data

== Create Database

.Create
[,sql]
----
drop database if exists dmpp_pedestal;
create database dmpp_pedestal character set utf8;
----

.Clean
[,sql]
----
insert into pedestal_citizen(id, name, mobile, deleted) values (uuid(), '鬼王', '13677889091', false);

select * from base_dict order by level;
select * from pedestal_citizen order by sort;
select * from pedestal_car_plate;
select * from pedestal_worker;
select * from pedestal_family;
select * from pedestal_contract;

delete from pedestal_contract where 1 = 1;
delete from pedestal_family where 1 = 1;
delete from pedestal_worker where 1 = 1;
delete from pedestal_car_plate where 1 = 1;
delete from pedestal_citizen where 1 = 1;
delete from base_dict where 1 = 1 order by level desc;
----

== Build and Deploy

.Build
[,bash]
----
./gradlew clean bootJar
docker build -t dmpp/service-pedestal .
----

.Deploy
[,bash]
----
docker run -d --name dmpp-pedestal -p 9717:9717 -e "DMPP_DATASOURCE_HOST=SERVER_IP" -e "MINIO_URL=http://SERVER_IP:PORT" dmmp/service-pedestal
----

== Initialization Data

.Dict
[,bash]
----
node init.js dict
----

.Pedestal
[,bash]
----
node init.js pedestal
----

== Mock Tests

[,bash]
----
./gradlew help --task test

--tests     Sets test class or method name to be included, '*' is supported.

./gradlew :service-pedestal:test --tests "org.thraex.dmpp.mock.MockTests"

./gradlew :service-pedestal:test --tests "org.thraex.dmpp.mock.MockTests" --info

./gradlew :service-pedestal:test --tests "org.thraex.dmpp.mock.MockTests$MockPrepareTests.mockDict"

./gradlew :service-pedestal:test --tests 'org.thraex.dmpp.initialization.Initialization*'

service-pedestal/src/test/java/org/thraex/dmpp/AbstractTests.java
service-pedestal/src/test/java/org/thraex/dmpp/initialization/InitializationAvatar.java
service-pedestal/src/test/java/org/thraex/dmpp/initialization/InitializationExcel.java
service-pedestal/src/test/java/org/thraex/dmpp/initialization/InitializationOther.java
service-pedestal/src/test/java/org/thraex/dmpp/initialization/InitializationPedestal.java

./gradlew :service-pedestal:test --tests 'org.thraex.dmpp.initialization.InitializationPedestal'
./gradlew :service-pedestal:test --tests 'org.thraex.dmpp.initialization.InitializationExcel'
./gradlew :service-pedestal:test --tests 'org.thraex.dmpp.initialization.InitializationAvatar'
./gradlew :service-pedestal:test --tests 'org.thraex.dmpp.initialization.InitializationOther'
----

API:
* ``/api/security/**``
* ``/api/pedestal/**``
* ``/api/fs/**``
* ``/api/message/**``
* ``/api/supplier/**``

== Nginx

[,bash]
----
$ docker run -d \
  --name c-nginx \
  -p 9710-9717:9710-9717 \
  -v $PWD/Workspace/Dockers/nginx/conf.d:/etc/nginx/conf.d \
  -v $PWD/Workspace/Dockers/nginx/html:/usr/share/nginx/html \
  nginx:1.21.6
----

link:https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container[How do I assign a port mapping to an existing Docker container?]

link:https://www.baeldung.com/linux/assign-port-docker-container[Assigning a Port Mapping to a Running Docker Container]

* Stop container and docker service
[,bash]
----
docker stop c-nginx
sudo systemctl stop docker
----

* Get full docker container ID: ``docker inspect --format="{{.Id}}" c-nginx``

* modify ``sudo vim /var/lib/docker/containers/38b3a4ef17d649f49f56a536a793633241ae2844d8336368e0eedf9a5a40a0de/hostconfig.json``, add ``,"9717/tcp":[{"HostIp":"","HostPort":"9717"}]`` at PortBindings

* Modify ``sudo vim /var/lib/docker/containers/38b3a4ef17d649f49f56a536a793633241ae2844d8336368e0eedf9a5a40a0de/config.v2.json
``, add ``,"9717/tcp":{}`` at ExposedPorts

* Start docker service and container
[,bash]
----
sudo systemctl start docker
docker start c-nginx
----

=== Other

link:https://docs.docker.com/config/daemon/systemd/[Control Docker with systemd]

* Flush changes and restart Docker
[,bash]
----
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
----
== Export and Import Databases

=== Run MySQL

[,bash]
----
$ docker run -d \
  --name c-mysql-prod \
  -p 3307:3306 \
  -v $PWD/Dockers/mysql-prod/conf:/etc/mysql/conf.d \
  -v $PWD/Dockers/mysql-prod/data:/var/lib/mysql \
  -v $PWD/Dockers/mysql-prod/logs: /log \
  -e MYSQL_ROOT_PASSWORD=hanzo \
  mysql:5.7
----

== Redis

[,bash]
----
$ docker run -d --name c-redis -p 6379:6379 redis:latest --requirepass hanzo
----
