:toc-title: Data Middle Platform of Personnel
// :toc: left
:toclevels: 4
:source-highlighter: rouge

= {toc-title}

== Important

- [ ] ✨Login
- [x] Avatar
- [x] Profiles修改
- [ ] 修改字段可配置
- [x] 质疑修改(工单)
- [x] 获取百分比
- [x] ✅后台手动百分比计算(AOP暂延)
- [x] ❌ Dicts API
- [x] Databases schema name
- [ ] Security...

- [ ] 数据初始化
- [ ] 项目构建 - Docker(F/B)
- [ ] 测试

- [ ] 下周一第一版测试

== Docs

- [ ] Profiles modify tests: `/supplier/profiles/changer`
- [ ] Get poportion tests: `/supplier/profiles/proportion`
- [ ] Reset poportion tests: `/supplier/profiles/proportion/reset`

== APIS

- [ ] Dict / Org findByCodes and unique api
- [x] Supplier profiles
- [x] ❌ Deprecated: Optimize profiles api performance
- [x] Profile completion percentage
- [x] Find Dict by codes
- [ ] AOP计算百分比

Adapter

== Tasks

- [ ] List / Page List query conditions(pagation)
- [ ] Fix method `org.thraex.toolkit.model.AbstractTree#toTree`
- [ ] **modules** refactored into microservices: modular / entity /service / repository
- [x] remove `thraex.supplier.mock-prefix`
- [ ] Optimization `@EnableGeneric` annotations, add `boolean genericRouterFunction() default true;`
- [ ] Refactor databases table name
- [ ] Refactor **Tests**, change MySQL to H2. Optimization performance
- [ ] Optimization security / token
- [ ] Remove `Avatar`
- [ ] `JpaEntity` change to `Auditable`
- [ ] `AuditorAware` -> `ReactiveAuditorAware`
- [ ] Foreign key for `@OneToMany`
- [ ] `CompletableFuture`

## Questions

- FamilyServiceImpl: // TODO: Question...
- Empty to null ? throw exception
- (if else) to (? :)
- Blank line

## Configuration

.main application-local.yml
[,yaml]
----
spring:
  jackson:
    default-property-inclusion: always
  datasource:
    url: jdbc:mysql://localhost:3307/dmpp_pedestal?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: hanzo
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true

logging:
  level:
    org.thraex: trace

thraex:
  security:
    token:
      exp: 720
#thraex:
#  security:
#    permitted:
#      - /docs/**
#      - /**
minio:
  url: http://localhost:9000
  access-key: root
  secret-key: minio-admin
  bucket: dev
  web-url: ${minio.url}/${minio.bucket}/
----

.test application-local.yml
[,yaml]
----
spring:
  jackson:
    default-property-inclusion: always
  datasource:
    url: jdbc:mysql://localhost:3307/dmpp_pedestal_docs?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: hanzo

debug: true

minio:
  url: http://localhost:9000
  access-key: root
  secret-key: minio-admin
  bucket: dev
  web-url: ${minio.url}/${minio.bucket}/
----